apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stackbot-deployment
  labels:
    app: stackbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackbot
  template:
    metadata:
      labels:
        app: stackbot
    spec:
      containers:
      - name: stackbot
        image: fancy.azurecr.io/stackoverflowbot:latest
        ports:
         - containerPort: 8080 
           protocol: TCP
        env:
          - name: PORT 
            value: "8080"
---
kind: Service
apiVersion: v1
metadata:
  name: stackbot-service
spec:
  selector:
    app: stackbot
#  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 8080 
     targetPort: 8080
     name: httpport
#   - protocol: TCP
#     port: 443 
#     targetPort: 443 
#     name: httpsport
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: stackbot-ingress
 annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
     - hosts: 
       - "stack-bot.fancy.cloud"
       secretName:  tls-fancy 
  rules:
  - host: stack-bot.fancy.cloud
    http:
     paths:
     - path: / 
       backend:
         serviceName: stackbot-service
         servicePort: httpport 
